Fix undefined reference to ulp_count and ulp_entry
Arduino doesn't seem to be copying the .s files from the sketch directory to the temp directory. This causes the following errors:
`undefined reference to 'ulp_count'` 
`undefined reference to 'ulp_entry'`.